### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [totigm/whatsapp-stickers-bot#1]
npm start

> whatsapp-stickers-bot@0.0.1 start /root/whatsapp-stickers-bot
> npm run dev

> whatsapp-stickers-bot@0.0.1 dev /root/whatsapp-stickers-bot
> nodemon --config nodemon.json src/index.ts

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/index.ts`
(node:76671) UnhandledPromiseRejectionWarning: Error: Failed to launch the brows    er process! spawn /root/whatsapp-stickers-bot/node_modules/puppeteer/.local-chro    mium/linux-982053/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troublesh    ooting.md

    at onClose (/root/whatsapp-stickers-bot/node_modules/puppeteer/src/node/Brow    serRunner.ts:268:9)
    at ChildProcess.<anonymous> (/root/whatsapp-stickers-bot/node_modules/puppet    eer/src/node/BrowserRunner.ts:257:9)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This     error originated either by throwing inside of an async function without a catch     block, or by rejecting a promise which was not handled with .catch(). To termin    ate the node process on unhandled promise rejection, use the CLI flag `--unhandl    ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti    ons_mode). (rejection id: 1)
(node:76671) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr    ecated. In the future, promise rejections that are not handled will terminate th    e Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart

**Comment by totigm** [comment]
Hey @bkzutr90! How are you doing?

Thanks for creating an issue.
Could you try pulling the latest changes? Earlier today I committed [📌 Update @totigm/whatsapp-bot version](https://github.com/totigm/whatsapp-stickers-bot/commit/45bad2bcd0cb5317954a9b6527040b28d7dd20be) due to WhatsApp web breaking changes.

Using [@totigm/whatsapp-bot](https://github.com/totigm/whatsapp-bot) latest version (v1.0.9) should fix it.

**Comment by bkzutr90** [comment]
> Hey @bkzutr90! How are you doing?
> 
> Thanks for creating an issue. Could you try pulling the latest changes? Earlier today I committed [pushpin Update @totigm/whatsapp-bot version](https://github.com/totigm/whatsapp-stickers-bot/commit/45bad2bcd0cb5317954a9b6527040b28d7dd20be) due to WhatsApp web breaking changes.
> 
> Using [@totigm/whatsapp-bot](https://github.com/totigm/whatsapp-bot) latest version (v1.0.9) should fix it.

:~/whatsapp-stickers-bot# npm start                 
> whatsapp-stickers-bot@0.0.1 start
> npm run dev


> whatsapp-stickers-bot@0.0.1 dev
> nodemon --config nodemon.json src/index.ts

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/index.ts`
Error: Failed to launch the browser process!
[1112/151147.513533:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/whatsapp-stickers-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/root/whatsapp-stickers-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by totigm** [comment]
This was fixed on the [📌 Update @totigm/whatsapp-bot version](https://github.com/totigm/whatsapp-stickers-bot/commit/48f160879309b70fd369b397fb5bad9911d82be7) commit.

Closing issue.
