### ISSUE TITLE
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

### ISSUE THREAD

**Issue by TrueIntelligence** [totigm/whatsapp-stickers-bot#3]
> whatsapp-stickers-bot@0.0.1 prod
> set NODE_ENV=prod && node ./dist/index.js

/workspaces/whatsapp-stickers-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspaces/whatsapp-stickers-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/workspaces/whatsapp-stickers-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by TrueIntelligence** [comment]
nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/index.ts`
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspaces/whatsapp-stickers-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at ChildProcess.<anonymous> (/workspaces/whatsapp-stickers-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:257:9)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by totigm** [comment]
Hey @xousef! I hope you are doing well.

I'm going to take a look into it. Could you please tell me which OS are you using?

Thanks!

**Comment by totigm** [comment]
This should be fixed with the latest changes.
